// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiJHGA_EqYIb2WTUPe6XPtfftRQPSB8_Y',
    appId: '1:319353603212:web:07863d2a39bea35e08e7a9',
    messagingSenderId: '319353603212',
    projectId: 'supermarket-place',
    authDomain: 'supermarket-place.firebaseapp.com',
    storageBucket: 'supermarket-place.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqFoRFJLUBODH99nUz4r9ZQMb3cA5MFRQ',
    appId: '1:319353603212:android:abad730a967046c908e7a9',
    messagingSenderId: '319353603212',
    projectId: 'supermarket-place',
    storageBucket: 'supermarket-place.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9So6T1TMF9PEgLc6uYuKQgP0zBsE6O4Y',
    appId: '1:319353603212:ios:20e31aec0374c6f608e7a9',
    messagingSenderId: '319353603212',
    projectId: 'supermarket-place',
    storageBucket: 'supermarket-place.appspot.com',
    iosBundleId: 'com.example.supermarketplace',
  );
}
